import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useSession, signIn, signOut } from "next-auth/react";


export default function Home() {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs Login GitHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1 className={styles.title}>
        Hi, I am <a href="https://horacio-abitu.vercel.app">Horacio!</a>
        </h1>

        <p className={styles.description}>
          This is a example Next Js of {' '}
          <code className={styles.code}>Login with GitHub and Google</code>
        </p>

        <div className={styles.containerlogin}>
        {!session && (
          <button className={styles.myButton} onClick={() => signIn()}>Sign in width...</button>
        )}
        {session && <button className={styles.myButton} onClick={() => signOut()}>Sign out ({session.user.name})</button>}
        <br />
        {session?.user && (
            <>
              {session.user.image && (
                <span
                  style={{ backgroundImage: `url('${session.user.image}')` }}
                  className={styles.avatar}
                />
              )}
              <span className={styles.signedInText}>
                <small>Signed in as {session.user.name}</small>
                <br />
                <strong>{session.user.email ?? session.user.name}</strong>
              </span>
              
            </>
          )}
        </div>

        <div className={styles.grid}>
          <a href="https://github.com/dev-back55" className={styles.card}>
            <h2>Github Repo &rarr;</h2>
            <p>Find the public repo in Github.</p>
          </a>

          <a href="https://nextjs.org/docs/authentication" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js Authentication in official documentation!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Example &rarr;</h2>
            <p>Deploy in Github Pages.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://horacio-abitu.vercel-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/developer.png" alt="Horacio Abitu" width={35} height={30} />
             {'  '}Horacio Abitú
          </span>
        </a>
      </footer>
    </div>
  )
}
